In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [127]:
X = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(4,3)
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [136]:
U = np.linalg.eigh(X.dot(X.T))
U[1]

array([[-0.29799196,  0.45956587, -0.82471435, -0.14087668],
       [ 0.05478243, -0.83486459, -0.42626394, -0.34394629],
       [ 0.78441101,  0.29103156, -0.02781353, -0.54701591],
       [-0.54120148,  0.08426716,  0.37063688, -0.75008553]])

In [139]:
V = np.linalg.eigh(X.T.dot(X))
V[1]

array([[ 0.40824829, -0.76077568, -0.50453315],
       [-0.81649658, -0.05714052, -0.5745157 ],
       [ 0.40824829,  0.64649464, -0.64449826]])

In [141]:
sq_v0 = np.sqrt(V[0])
sq_v0[np.isnan(sq_v0)]=0
ram = np.diag(np.sort(sq_v0)[::-1])
ram

C:\Users\RAKUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[25.46240744,  0.        ,  0.        ],
       [ 0.        ,  1.29066168,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [138]:
np.delete(U[1],3,1).dot(ram).dot(V[1].T)

array([[ 505.15407228,   44.64993573,   44.93560712],
       [ 264.7295561 ,  -24.64492306,  -59.43423138],
       [  16.76325129,  -23.27138489,   39.26679025],
       [-228.48986585,   19.88601651,   -9.82255243]])

In [128]:
u,s,v = np.linalg.svd(X, full_matrices=False)

In [129]:
u.dot(np.diag(s).dot(v))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [130]:
u

array([[-0.14087668,  0.82471435,  0.53358462],
       [-0.34394629,  0.42626394, -0.8036038 ],
       [-0.54701591,  0.02781353,  0.00645373],
       [-0.75008553, -0.37063688,  0.26356544]])